server:
  port: 62

spring:
  application:
    name: transactionservice
  data:
    mongodb:
      uri: mongodb+srv://umsul:UmsulDB@clusterws.gvpnecc.mongodb.net/kasirdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:72/eureka

